// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQQOPOOO]OPO'#C`OOOO'#Cc'#CcOOOO'#Ca'#CaQQOPOOOOOO,58z,58zOkOPO,58zOOOO-E6_-E6_OOOO1G.f1G.f",
  stateData: "y~OQQORQOXPO~OQQORQOWTOXPO~OQQORQOWWOXPO~O",
  goto: "oWPPPPX_PiXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ Program Identifier Name Application",
  maxTerm: 9,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!]~RSxy_yzd!c!}i#T#oz~dOX~~iOW~~nSR~!Q![i!c!}i#R#Si#T#oi~!PSQ~!Q![z!c!}z#R#Sz#T#oz",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
