// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
const spec_Identifier = {__proto__:null,int:18}
export const parser = Parser.deserialize({
  version: 13,
  states: "!pQVQPOOPbOPOOOOQO'#Cb'#CbQVQPOOOgQPO'#C`OOQO'#Cf'#CfPVQPO'#C]POOO)C>Y)C>YOOQO-E6`-E6`OuQPO,58zOOQO,58z,58zPOOO,58w,58wOOQO1G.f1G.f",
  stateData: "!T~OXPQ~OQTORTO[SO~OXUO~OQTORTOZYO[SO~OQTORTOZ[O[SO~O",
  goto: "yZP[PP_PfPPPpRVPZTORSUXQROSWRXRXSWQORSXRZU",
  nodeNames: "⚠ NewExpression Identifier Name Application Program",
  maxTerm: 12,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "!]~RSxy_yzd!c!}i#T#oz~dO[~~iOZ~~nSR~!Q![i!c!}i#R#Si#T#oi~!PSQ~!Q![z!c!}z#R#Sz#T#oz",
  tokenizers: [0],
  topRules: {"Program":[0,5]},
  specialized: [{term: 2, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
