// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "!WQQOPOOO`OPO'#CaOOOO'#Cd'#CdOOOO'#Cb'#CbQQOPOOOOOO,58{,58{OqOPO,58{OOOO-E6`-E6`OOOO1G.g1G.g",
  stateData: "!S~OQQORQOSQOYPO~OQQORQOSQOXTOYPO~OQQORQOSQOXWOYPO~O",
  goto: "pXPPPPPY`PjXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ Program Identifier Name Number Application",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!e~RTxybyzg!Q![l!c!}q#T#o!S~gOY~~lOX~~qOS~~vSR~!Q![q!c!}q#R#Sq#T#oq~!XSQ~!Q![!S!c!}!S#R#S!S#T#o!S",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
